--- 
abstract: A Str type parameterised by length
author: 
  - Chris Andrews <chris@nodnol.org>
generated_by: me
license: perl
name: MooseX-Types-Varchar
requires: 
  Moose: 0
  MooseX::Types: 0
version: 0.01
